# Generated by Django 4.2.17 on 2025-12-19 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='MYR', max_length=20)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='farm.crop')),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'db_table': 'MARKET_PRICE',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
