# Generated by Django 4.2.17 on 2025-12-19 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryLog',
            fields=[
                ('advisory_id', models.AutoField(primary_key=True, serialize=False)),
                ('advisory_type', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilization', 'Fertilization'), ('pest_control', 'Pest Control'), ('harvest', 'Harvest'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('executed', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='farm.crop')),
                ('farm_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='farm.farmplot')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisory Log',
                'verbose_name_plural': 'Advisory Logs',
                'db_table': 'ADVISORY_LOG',
                'ordering': ['-created_at'],
            },
        ),
    ]
