# Generated by Django 4.2.17 on 2025-12-19 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('optimal_temperature_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimal_temperature_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimal_moisture_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimal_moisture_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimal_humidity_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optimal_humidity_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('growth_duration_days', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
                'db_table': 'CROP',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmPlot',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('size_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('sandy', 'Sandy'), ('loamy', 'Loamy'), ('silty', 'Silty'), ('peat', 'Peat'), ('chalky', 'Chalky')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_plots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Plot',
                'verbose_name_plural': 'Farm Plots',
                'db_table': 'FARM_PLOT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ph_level', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('farm_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='farm.farmplot')),
            ],
            options={
                'verbose_name': 'Sensor Data',
                'verbose_name_plural': 'Sensor Data',
                'db_table': 'SENSOR_DATA',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantingRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('expected_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planted', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_records', to='farm.crop')),
                ('farm_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planting_records', to='farm.farmplot')),
            ],
            options={
                'verbose_name': 'Planting Record',
                'verbose_name_plural': 'Planting Records',
                'db_table': 'PLANTING_RECORD',
                'ordering': ['-planting_date'],
            },
        ),
    ]
